### ISSUE TITLE
walmart有上传商品item的接口吗

### ISSUE THREAD

**Issue by dt7-wcf** [EalenXie/sdk-all#10]
您好 walmart有上传商品item的接口吗

**Comment by EalenXie** [comment]
SDK 暂未维护 。看看该接口是否是你需要的： https://developer.walmart.com/api/us/mp/items#operation/itemBulkUploads

**Comment by dt7-wcf** [comment]
> SDK 暂未维护。查看该接口是否是您需要的：https://developer.walmart.com/api/us/mp/items#operation/itemBulkUploads

是的 他只能通过multipart/form-data 进行提交吗
